@extends('home.includes.layout', ['title' => 'About College'])

@section('content')
    <div class="page-wrapper">

        <header class="page-heading clearfix">
            <div class="text-effect" data-content="About College">
                <span>Student Corner</span>
            </div>
            <!--//breadcrumbs-->
        </header>
        <div class="page-content">
                
                    <div class="vertical-tab mb-2" role="tabpanel">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#Section1" aria-controls="Section1" role="tab" data-toggle="tab">Academic Calandar</a></li>
                            <li role="presentation" ><a href="#Section2" aria-controls="Section2" role="tab" data-toggle="tab">Student Election</a></li>
                            <li role="presentation" ><a href="#Section3" aria-controls="Section3" role="tab" data-toggle="tab">Certificate / Diploma Course</a></li>
                            <li role="presentation" ><a href="#Section4" aria-controls="Section4" role="tab" data-toggle="tab">Value Added Course</a></li>
                            <li role="presentation" ><a href="#Section5" aria-controls="Section5" role="tab" data-toggle="tab">Internship / Training </a></li>
                            <li role="presentation" ><a href="#Section6" aria-controls="Section6" role="tab" data-toggle="tab">Teachers With Phd.D.</a></li>
                            <li role="presentation" ><a href="#Section7" aria-controls="Section7" role="tab" data-toggle="tab">Other State Faculties</a></li>
                            <li role="presentation" ><a href="#Section8" aria-controls="Section8" role="tab" data-toggle="tab">Research</a></li>
                            <li role="presentation" ><a href="#Section9" aria-controls="Section9" role="tab" data-toggle="tab">Books / Publications</a></li>
                            <li role="presentation" ><a href="#Section10" aria-controls="Section10" role="tab" data-toggle="tab">ICT Class Rooms</a></li>
                            <li role="presentation" ><a href="#Section11" aria-controls="Section11" role="tab" data-toggle="tab">E-Pathshala</a></li>
                            <li role="presentation" ><a href="#Section12" aria-controls="Section12" role="tab" data-toggle="tab">E-Governance</a></li>
                            <li role="presentation" ><a href="#Section13" aria-controls="Section13" role="tab" data-toggle="tab">Library</a></li>
                            <li role="presentation" ><a href="#Section14" aria-controls="Section14" role="tab" data-toggle="tab">Internet/Wifi Facility</a></li>
                            <li role="presentation" ><a href="#Section15" aria-controls="Section15" role="tab" data-toggle="tab">Scholarship</a></li>
                            <li role="presentation" ><a href="#Section16" aria-controls="Section16" role="tab" data-toggle="tab">Strategy Development and Deployment</a></li>
                            <li role="presentation" ><a href="#Section17" aria-controls="Section17" role="tab" data-toggle="tab">Culture</a></li>
                        </ul>
                        <!-- Tab panes -->
                        
                        <div class="tab-content tabs">
                            <div role="tabpanel" class="tab-pane fade in active" id="Section1">
                                <h3>Academic Calandar</h3>
                                <ul>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2023/07/academic-calende.jpg" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_2016-17</span></a></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2022/12/2018-21.jpg" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_ 2018-21</span></a></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2022/12/2019-20.jpg" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_ 2019-20</span></a></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2020-21.pdf" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_ 2020-21</span></a><div class="sendToPdfFiller" data-url="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2020-21.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2021-22.pdf" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_ 2021-22</span></a><div class="sendToPdfFiller" data-url="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2021-22.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2022-23.pdf" target="_blank" rel="noopener"><span data-msg="view">Academic Calendar_ 2022-23</span></a><div class="sendToPdfFiller" data-url="https://rkclnmu.ac.in/wp-content/uploads/2022/12/Academic-Calendar_-2022-23.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                    <li><a href="https://rkclnmu.ac.in/wp-content/uploads/2023/07/PG-ACADEMIC-CALENDER.pdf" target="_blank" rel="noopener"><span data-msg="view">PG Academic Calendar</span></a><div class="sendToPdfFiller" data-url="https://rkclnmu.ac.in/wp-content/uploads/2023/07/PG-ACADEMIC-CALENDER.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                </ul>
                            </div>
                            
                            <div role="tabpanel" class="tab-pane fade in " id="Section2">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section3">
                                <div class="row">
                                    <div class="col-md-4">
                                        <ul>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409004.pdf" target="_blank" rel="noopener">17407409004</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409004.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409005.pdf" target="_blank" rel="noopener">17407409005</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409005.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409006.pdf" target="_blank" rel="noopener">17407409006</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409006.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409007.pdf" target="_blank" rel="noopener">17407409007</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409007.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409008.pdf" target="_blank" rel="noopener">17407409008</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409008.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409009.pdf" target="_blank" rel="noopener">17407409009</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409009.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409010.pdf" target="_blank" rel="noopener">17407409010</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409010.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409011.pdf" target="_blank" rel="noopener">17407409011</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409011.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409012.pdf" target="_blank" rel="noopener">17407409012</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409012.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409013.pdf" target="_blank" rel="noopener">17407409013</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409013.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409014.pdf" target="_blank" rel="noopener">17407409014</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409014.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409015.pdf" target="_blank" rel="noopener">17407409015</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409015.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409016.pdf" target="_blank" rel="noopener">17407409016</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409016.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409017.pdf" target="_blank" rel="noopener">17407409017</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409017.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-4">
                                        <ul>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409018.pdf" target="_blank" rel="noopener">17407409018</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409018.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409019.pdf" target="_blank" rel="noopener">17407409019</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409019.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409020.pdf" target="_blank" rel="noopener">17407409020</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409020.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409021.pdf" target="_blank" rel="noopener">17407409021</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409021.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409022.pdf" target="_blank" rel="noopener">17407409022</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409022.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409023.pdf" target="_blank" rel="noopener">17407409023</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409023.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409024.pdf" target="_blank" rel="noopener">17407409024</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409024.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409025.pdf" target="_blank" rel="noopener">17407409025</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409025.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409026.pdf" target="_blank" rel="noopener">17407409026</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409026.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409027.pdf" target="_blank" rel="noopener">17407409027</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409027.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409028.pdf" target="_blank" rel="noopener">17407409028</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409028.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409029.pdf" target="_blank" rel="noopener">17407409029</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409029.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409030.pdf" target="_blank" rel="noopener">17407409030</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409030.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409031.pdf" target="_blank" rel="noopener">17407409031</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409031.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409032.pdf" target="_blank" rel="noopener">17407409032</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409032.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            </ul>
                                    </div>
                                    <div class="col-md-4">
                                        <ul>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409033.pdf" target="_blank" rel="noopener">17407409033</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409033.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409034.pdf" target="_blank" rel="noopener">17407409034</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409034.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409035.pdf" target="_blank" rel="noopener">17407409035</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409035.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409036.pdf" target="_blank" rel="noopener">17407409036</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409036.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409037.pdf" target="_blank" rel="noopener">17407409037</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409037.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409038.pdf" target="_blank" rel="noopener">17407409038</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409038.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409039.pdf" target="_blank" rel="noopener">17407409039</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409039.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409040.pdf" target="_blank" rel="noopener">17407409040</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409040.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409041.pdf" target="_blank" rel="noopener">17407409041</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409041.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409042.pdf" target="_blank" rel="noopener">17407409042</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409042.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409043.pdf" target="_blank" rel="noopener">17407409043</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409043.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409044.pdf" target="_blank" rel="noopener">17407409044</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409044.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            <li><a href="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409045.pdf" target="_blank" rel="noopener">17407409045</a><div class="sendToPdfFiller" data-url="http://rkclnmu.ac.in/wp-content/uploads/2019/10/17407409045.pdf" style="position: static; width: 40px; display: inline-block; margin-left: 10px;" title="Open with pdfFiller"><img style="background: none" src="chrome-extension://gphandlahdpffmccakmbngmbjnjiiahp/img/icon-fill.png"></div></li>
                                            </ul>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section4">

                                In pending 'https://lnmuacin.in/studentnotice/PG%20Subjects/Botany%20CBCS-min.pdf'
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section5">
                                <div class="row">
                                    <div class="col-md-12">
                                        <img class="aligncenter wp-image-1164 size-full" src="http://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-1.jpg" alt="" width="757" height="547" srcset="https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-1.jpg 757w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-1-300x217.jpg 300w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-1-750x542.jpg 750w" sizes="(max-width: 757px) 25vw, 757px">
                                    </div>
                                    <div class="col-md-12">
                                        <img class="aligncenter wp-image-1165 size-full" src="http://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-2.jpg" alt="" width="949" height="701" srcset="https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-2.jpg 949w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-2-300x222.jpg 300w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-2-768x567.jpg 768w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-2-750x554.jpg 750w" sizes="(max-width: 949px) 25vw, 949px">
                                    </div>
                                    <div class="col-md-12">
                                        <img class="aligncenter wp-image-1166 size-full" src="http://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-3.jpg" alt="" width="835" height="625" srcset="https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-3.jpg 835w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-3-300x225.jpg 300w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-3-768x575.jpg 768w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-3-750x561.jpg 750w" sizes="(max-width: 835px) 25vw, 835px">
                                    </div>
                                    <div class="col-md-12">
                                        <img class="aligncenter wp-image-1168 size-full" src="http://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5.jpeg" alt="" width="1047" height="713" srcset="https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5.jpeg 1047w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5-300x204.jpeg 300w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5-768x523.jpeg 768w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5-1024x697.jpeg 1024w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-5-750x511.jpeg 750w" sizes="(max-width: 1047px) 25vw, 1047px">
                                    </div>
                                    <div class="col-md-12">
                                        <img class="aligncenter wp-image-1167 size-full" src="http://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-4.jpg" alt="" width="999" height="725" srcset="https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-4.jpg 999w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-4-300x218.jpg 300w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-4-768x557.jpg 768w, https://rkclnmu.ac.in/wp-content/uploads/2019/10/INTERNSHIP-4-750x544.jpg 750w" sizes="(max-width: 999px) 100vw, 999px">
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section6">
                                <img src="{{ asset('uploads/uploads/photo-gallery/teacher/Dr._S.A.AFSAH_(1)e091.jpg') }}" alt="">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section7">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section8">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section9">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section10">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section11">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section12">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section13">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section14">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section15">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section16">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section17">
                            </div>
                            <div role="tabpanel" class="tab-pane fade in " id="Section18">
                            </div>
                        </div>
                    </div>
        </div>
    </div>
@endsection    